apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-watcher-operator
  labels:
    app: config-watcher-operator
spec:
  selector:
    matchLabels:
      app: config-watcher-operator
  template:
    metadata:
      labels:
        app: config-watcher-operator
    spec:
      serviceAccountName: config-watcher-operator
      containers:
      - name: proxycontainer
        image: lachlanevenson/k8s-kubectl
        command: ["kubectl","proxy","--port=8001"]
      - name: app
        image: vikasit/operator
        env:
          - name: res_namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

