# Service account required for watching to resources
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-watcher-operator
---
# Bind to an appropriate permission
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-watcher:edit
subjects:
- kind: ServiceAccount
  name: config-watcher-operator
roleRef:
  name: edit
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-watcher:crd
subjects:
- kind: ServiceAccount
  name: config-watcher-operator
roleRef:
  name: config-watcher-crd
  kind: Role
  apiGroup: rbac.authorization.k8s.io